package network;

public enum Responses { // possible flags (messages) Server can send to client

	SERVER_NOTIFIES_TURN, CLIENT_JOINED_TO_SERVER, FULL_LOBBY, PING_TO_CLIENT, SEND_INITIAL_WAITING_TIME_TO_CLIENT, 
	SEND_WELLCOME_TO_GAME_TO_CLIENT, NEXT_ROUND_NAMES_TO_CLIENT, SERVER_NOTIFIES_CLIENT_TO_TRY, 
	TO_GUESS_NUMBER_IS_SMALLER, CLIENT_FAILED, CONGRATULATION, TO_GUESS_NUMBER_IS_BIGGER, ASKS_TO_CLIENT_TO_TRY, 
	ON_WAIT_FOR_ROUND_PARTNERS_TO_FINISH, ROUND_FINAL_OPTIONS_ASKED_TO_CLIENT, CLIENT_REMOVED, KEEP_ALIVE, TIME_OUT, 
	CLIENT_MOVED_TO_END_OF_QUEUE, CURRENT_ROUND_RANK;
}
